apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: "{{ include "aws-target-group-bindings.fullname" . }}"
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.service.name }}
  serviceRef:
    name: {{ .Values.service.name }}
    port: {{ int .Values.service.port }}
  {{- else if .Values.nodeSelector }}
  nodeSelector:
    matchLabels:
    {{- range $k, $v := .Values.nodeSelector }}
      {{ $k }}: {{ $v }}
    {{- end }}
  {{- end }}
  targetGroupARN: {{ required "TargetGroup ARN is Required" .Values.targetGroupARN }}
  targetType: {{ .Values.targetType | default "ip" }}