{{- if .Values.config.values }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
data:
    {{- range $k, $v := .Values.config.values }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}