{{- if .Values.secret.values }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.secret.type }}
  data:
    default-name: {{ include "api.fullname" . }}
    {{- range $k, $v := .Values.secret.values }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}